---

- name: install Development Tools
  yum: name="@Development tools" state=present
  sudo: yes

- name: install pip
  yum: name=python-pip state=latest
  sudo: yes

- name: install ansible dependency modules
  pip: name=httplib2 state=latest
  sudo: yes

- include: imagemagick.yml
